# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-MIME-Attachment-Stripper
version:      1.3
version_from: lib/Email/MIME/Attachment/Stripper.pm
installdirs:  site
requires:
    Email::MIME:                   1.8
    Email::MIME::Encodings:        1.1
    Test::More:                    0.45

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
